import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/navbar'
import styles from '../styles/About.module.css'

const About: NextPage = () =>
{
	return (
		<div className={styles.container}>
		<Head>
			<title>Forixaim</title>
		<meta name = "description" content = "Generated by create next app"/>
		<link rel="icon" href = "/favicon.ico"/>
		</Head>
			<header>
				<Navbar/>
		</header>
		<main className={styles.main}>
			<h1>sus </h1>
		</main>
		<footer>
			<p>Website by Forixaim. Powered by Next.js!</p>
		</footer>
		</div>
	)
}

export default About